brilliantshell/ft_transcendence

- docker-compose.dev.yml
- Issue #16  내용대로 클러스터 Docker Version 이슈 때문에 하위 버전에서도 돌아가게 하기 위해서 `docker-compose.dev.yml` 수정했습니다.
- `name` 디렉티브는 지웠습니다.
- database 개발 환경의 `configs` 디렉티브는 bind mount 로 대체했습니다.
close #16
> 🔨 chore : 클러스터 docker 버전 이슈에 따른 docker-compose.dev.yml 수정

- database/sql/init_db.sql
- #37 사항 반영
- `init_db.sql` 에서 `is_dm boolean` 을 `dm_peer_id integer FK` 로 수정
[노션 페이지](https://teal-grill-819.notion.site/DB-0390ec95162a4509aeb18cedbce3e7f2)에 업데이트 완료
close #37
> 🔨 chore : channels 테이블에서 is_dm 을 dm_peer_id 로 변경 #37

- .gitignore
- backend/src/app.controller.ts
- backend/src/app.module.ts
- backend/src/config/api-config.module.ts
- backend/src/config/api-config.service.spec.ts
- backend/src/config/api-config.service.ts
- backend/src/main.ts
- import 규칙 수정
- import 규칙에 맞게 순서 수정
- TypeORM entity 링크 규칙 수정
- 모듈 import 규칙 수정
- 패키지가 우선하고, 개행 하나 이후 작성한 모듈을 작성 이후 알파벳 순으로 정렬
> :recycle: refactor : import 순서 변경 및 TypeORM 링크 규칙 수정

- backend/src/app.module.ts
- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.interface.ts
- backend/src/chats/chats.module.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/user-status.module.ts
- backend/test/chats-gateway.e2e-spec.ts
- #71 작업
- ChatsGateway 에서 ActivityGateway 를 통한 Room 관리
- 채팅방의 멤버를 관리하는 `chatRooms-${channelId}` , 채팅방 UI 를 보고있는 멤버를 관리하는 `chatRooms-${channelId}-active` rooms 를 만들어서 접속 시 멤버들을 room 에 추가
- 채팅방 UI 에서 다른 UI 로 이동 시 `chatRooms-${channelId}-active` room 에서 제외
- 로그인 후 채팅방 UI 에 접속하기 전 Room 관리는 구현 미완료(까먹었습니다...)
- chats interface 파일 생성 및 interface 선언
- ActivityGateway 에서 유저가 특정 채팅방에 접속 시 ChannelStorage 를 통한 unseenCount 초기화
- ActivityGateway 의 handleConnection 메소드에서 chats socket Room 에 넣는 로직 추가
--- 
- unseenCount 나 ActivityGateway 와 함께 작동하는 부분은 보완이 필요합니다.
- 각종 validation 이 필요한 부분은 service 구현까지 가봐야 가닥이 잡힐 듯 싶어서 주석만 달아뒀습니다.
- #71 은 제가 내일 한번 더 검토해보고 직접 닫겠습니다.
> ✨ feat : chat WS 이벤트 핸들링 하는 ChatsGateway 구현

- backend/src/user/dto/user-info.dto.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.gateway.ts
- backend/src/util/type.ts
- backend/test/user-gateway.e2e-spec.ts
- #65 완성
- 아래 이벤트들 emitter 생성.
- 친구 요청 수락 (`friendAccepted`)
- 친구 요청 거절 (`friendDecliend`)
- 친구 요청 취소 (`friendCancelled`)
- 친구 요청 수신 여부 확인 (`pendingFriendRequest`)
- 친구 삭제 (`friendRemoved`)
- 차단 (`blocked`)
- 차단 해제 (`unblocked`)
- [`friendRemoved`](https://www.notion.so/WebSocket-API-d8355825129b4b2e9f6fc83fdf5e1c7b#73d46fc97fb3442bb1343abbc0fb8456), [`blocked`](https://www.notion.so/WebSocket-API-d8355825129b4b2e9f6fc83fdf5e1c7b#be362c45f32740e8afbe87904f227c14), [`unblocked`](https://www.notion.so/WebSocket-API-d8355825129b4b2e9f6fc83fdf5e1c7b#1b56371b2c004bce99067dc1e2fddfb2) 이벤트들은 설계에 누락 돼있어 설계에도 추가했습니다.
- `emitUserInfo` method 에서 DTO 데이터 추리는 과정을 UserService 의 역할이라고 판단해 분리하고, 테스트에 반영했습니다.
close #65
> ✨ feat : userComponent & friendsToggle 관련 WS 이벤트 핸들링하는 UserGateway 객체 구현

- backend/src/chats/chats.controller.ts
- backend/src/chats/chats.module.ts
- backend/src/chats/chats.service.spec.ts
- backend/src/chats/chats.service.ts
- backend/src/chats/dto/chats.dto.ts
- backend/src/chats/mock-auth/mock-auth.guard.ts
- backend/test/chats.e2e-spec.ts
- #87 완료
- ChatsService 에 #80 PR 에서 ghan 님이 언급해주신 사항 반영 및 리팩토링
- 간략한 Validation 과 함께 `ChatsController` 구현
- ChatsController 내부의 Validation 및 ChatsService 에서 중복되는 Validation 은 다음 PR 에 pipe 나 guard 로 분리할 계획입니다.
- userId 를 넣어주기 위한 MockAuthGuard 구현
- 나중에 AuthGuard 가 구현되면 해당 Guard 로 교체할 예정입니다.
---
- #80 PR 에서 채팅방 한글 정렬이 안된다고 언급했는데, string.localeCompare 가 유니코드순 정렬이라서 한글도 잘 정렬된다고 합니다. 숫자 - 알파벳 - 한글 정렬을 위해선 localeCompare 을 사용하면 되고, 숫자 - 한글 - 알파벳 정렬을 하고 싶으면`.sort(new Intl.Collator('ko').compare))` 이런 식으로 하면 된다고 합니다... [참고 링크](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator)
> ✨ feat : /chats 로 오는 요청을 처리하는 ChatsController 구현 #87

- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/dto/user-status.dto.ts
- backend/src/user-status/user-status.module.ts
- backend/src/user/dto/user-gateway.dto.ts
- backend/src/user/guard/accept-friend.guard.ts
- backend/src/user/guard/blocked-user.guard.ts
- backend/src/user/guard/create-friend-request.guard.ts
- backend/src/user/guard/delete-block.guard.ts
- backend/src/user/guard/delete-friend.guard.ts
- backend/src/user/guard/self-check.guard.ts
- backend/src/user/guard/user-exist.guard.ts
- backend/src/user/user.gateway.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
- backend/test/activity-gateway.e2e-spec.ts
- backend/test/user.e2e-spec.ts
- #97 완료
- activity 초기값 및 변경 알리는 `userActivity` 이벤트 설정.
- 유저가 처음으로 `currentUi` 이벤트로 activity 설정할 때 emit.
- WS disconnection 시 emit.
- `GET /user/:userId/info` 요청 받았을 때 당시 해당 유저의 activity 정보 emit.
- 관계 초기값 및 변경 알리는 이벤트들 `userRelationship` 으로 통합.
- 에러 메시지에 id 명시.
- ActivityGateway 에서 `userActivity` 이벤트 emit.
close #97
> ♻️ refactor : 관계 변화 & activity 변화 업데이트

- backend/test/generate-mock-data.ts
- ProfileService 테스트를 위한 Achievers, Achievements, MatchHistory entity 생성 스크립트 추가
- MatchHistory 기반으로 Users entity 업데이트하는 스크립트 추가
---
Achievement 상세 내용을 추후에 정해야 할 것 같습니다. 지금은 테스트를 위해 생각나는대로 작성한 상태입니다.
> :hammer: chore : Achievers, Achievements, MatchHistory entity 생성 스크립트 추가

- backend/src/app.module.ts
- backend/src/chats/chats.module.ts
- backend/src/game/dto/game-gateway.dto.ts
- backend/src/game/game.gateway.ts
- backend/src/game/game.module.ts
- backend/src/game/game.storage.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/channel.storage.spec.ts
- backend/src/user-status/user-status.module.ts
- backend/src/util/type.ts
- backend/test/game-gateway.e2e-spec.ts
- #100 진행 중
- #101 진행 중
- 뜻밖의 #105 가 발견됐고, 너무 커질 것 같아 중간에 PR 한번 합니다.
- 게임 설계에 허점이 많았어서 구현하며 동적 설계를 병행하고 있습니다. 동의하지 않는 설계/구현이 보이시면 말씀해주세요 :)
- 게임 매칭되면 매칭된 유저에게 gameId 전달해주며 알리는 `newGame` emitter 구현.
- 게임 옵션 설정 relay 하는 `gameOption` emitter 구현.
- 새 게임 시작을 waitingRoom UI 에 있는 유저들에게 알리는 `gameStarted` emitter 구현.
- 게임 정상 종료 시 클라이언트가 보내는 `gameComplete` 이벤트 listner 구현.
- 게임 종료 후 결과 DB 에 업데이트 하는 `GameService.updateResult` 구현.
- #105 임시 처리. 일단 문제가 생기는 곳에서 undefined 체크 해주는데, 이게 충분할지... 내일 클러스터 오시면 같이 이야기해보죠 @yongjulejule.
- UserStatusModule 에서 ChatsGateway 를 provider 로 받고 있었습니다. 이렇게 되면 ChatsGateway 가 두 모듈에서 provider 로 불리기 때문에 두번 인스턴스화 됩니다(어떻게 알았는지 물으신다면 저도 알고싶지 않았습니다...이벤트를 두번씩 listen...). 따라서 UserStatusModule 에 ChatsModule 을 모듈로 import 받도록 설정했습니다. Circular dependency 를 해결하기 위해 양 모듈에서 `forwardRef` …
> :sparkles: feat : GameGateway & GameStorage 부분 구현

- backend/src/ranks/dto/ranks.dto.ts
- backend/src/ranks/ranks.module.ts
- backend/src/ranks/ranks.service.spec.ts
- backend/src/ranks/ranks.service.ts
- #121 완료
- 요청한 유저의 랭킹 & 전체 유저 수 반환하는 findPosition 구현.
- 사용한 query 가 조금 복잡한데 comment 달아두겠습니다.
- offset 부터 limit 만큼의 유저들을 찾아서 랭킹순으로 id, ladder, rank 반환하는 findLadders 구현.
- userId 다시 id 로 바꿨습니다.
- query range 체크는 controller 구현하면서 하겠습니다.
- postgresql RANK() 함수가 공동 순위까지 다 계산해줘서 서버에서 순위 정보까지 포함해서 보내는 걸로 수정했습니다. 노션 API 설계에도 수정해뒀습니다.
close #121
> ✨ feat : 유저 랭킹 반환하는 RanksService 구현

- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- #131 완료
- asset directory 를 호스팅 하며 옵션을 잡아줬습니다.
- 캐싱 설정은 nest.js 가 잘 해주는것 같아 손대지 않았습니다. [옵션별 설명](https://github.com/nestjs/serve-static/blob/master/lib/interfaces/serve-static-options.interface.ts)
- 제가 설정한 옵션에 대한 설명은 코멘트 달아두겠습니다.
- static serve 를 위한 패키지를 설치했습니다.
- 확장자 없이 잘 작동하는지 확인하기 위해 nginx 로 간단한 테스트를 해봤습니다.
- svg 제외하곤 모두 잘 됩니다.
- 개발자도구의 네트워크 탭을 뜯어보니 확장자가 없는 경우 content-type 을 application/octet-stream 으로 보내는데, svg 는 binary data 가 아니라서 안되는거 같습니다.
- 프사에 svg 를 지원하지 않는게 적절한 해결책이라 생각합니다. ㅎㅎ
> ✨ feat : 유저들의 ProfileImage 가 저장되는 디렉토리 static  호스팅

- backend/src/game/dto/game-gateway.dto.ts
- backend/src/game/dto/game.dto.ts
- backend/src/game/game.controller.ts
- backend/src/game/game.gateway.ts
- backend/src/game/game.module.ts
- backend/src/game/game.service.spec.ts
- backend/src/game/game.service.ts
- backend/src/game/guard/in-game-ui.guard.ts
- backend/src/game/guard/in-play.guard.ts
- backend/src/game/interceptor/ladder-queue.interceptor.ts
- backend/src/game/interceptor/ladder-start.interceptor.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/util/type.ts
- backend/test/game-gateway.e2e-spec.ts
- backend/test/game.e2e-spec.ts
- backend/test/util/util.ts
- #139 완료
- queue timeout 은 다음 PR 에 추가하겠습니다.
- queue 코드가 조금 복잡해서 comment 로 최대한 설명해놓겠습니다. 그리고 notion 에 게임 관련 data flow 를 문서화할 예정입니다... 빠른 시일 내로...
- 아래 route 들 구현했습니다.
- waitingRoom 에서 진행 중인 게임 array 를 얻기 위해 요청하는 `GET /game/list`.
- waitingRoom/userComponent 에서 관전자가 게임방 UI 를 그리기 위해 필요한 정보를 요청하는 `GET /game/list/:gameId`.
- ladder game 매칭 큐에 유저를 추가하는 `POST /game/queue`.
- 플레이어가 게임방 그리는데 필요한 정보 요청하는 `GET /game/:gameId`
- 일반 게임 map 변경하는 `PATCH /game/:gameId/options`.
- 게임 동시 시작 trigger 하는 `PATCH /game/:gameId/start`.
- 플레이어들과 관전자에게 라이브 game 중개해주는 emitGameStatus 는 임시로 만들어뒀습니다.
- ladder 게임인지, 일반 게임인지 게임방 UI 에서 표시해주면 좋을 것 같아 해당 정보를 client 로 전달해주도록 `GET /game/list/:gameId`(관전자) & `GET /game/:gameId`(플레이어) res.body 를 수정했습니다. 
- ladder 게임의 경우 ui 에 들어가면 바로 실행되지만, 일반 게임의 경우 맵 설정 후 게임이 시작되어야하기 때문에 기존 …
> ✨ feat : /game 으로 오는 요청 처리하는 GameController 구현

- backend/src/auth/jwt-auth.io-adapter.ts
- backend/src/config/constant/constant-config.ts
- backend/src/main.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/util/type.ts
- backend/test/activity-gateway.e2e-spec.ts
- backend/test/auth.e2e-spec.ts
- backend/test/chats-gateway.e2e-spec.ts
- #62 완료
- WebSocket 에서 access / refresh 토큰 인증
- 인증과정에 필요한 타입 추가 (VerifiedWsRequest, VerifiedSocket)
- 인증 실패시 client 에서 다음과 같이 핸들링 하면 될 것 같습니다.
```tsx
const nav = useNavigate();
const socket = io('http://localhost:3000', { withCredentials: true }); // socket 연결 시 자동으로 서버에서 인증 실행
socket.io.on('error', (error: any) => {
alert('connect_error'); // error message
socket.close();
nav('/login'); // 로그인 페이지로 redirect
});
```
- WEBSOCKET_CONFIG 에 cookie 옵션 삭제
- 서버가 1개인 경우는 필요 없다고 나와 있어서 삭제했습니다 [socket.io 설명](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/#no-more-cookie-by-default)
---
- `backend/test/auth.e2e-spec.ts` 파일에 diff 가 너무 많이 뜨는데, 실제로 추가된 부분은 283번 라인 이후입니다.
> :sparkles: feat :  WS connection 인증하는 JwtAuthIoAdapter 구현

- frontend/.env.sample
- frontend/src/style/App.css
- frontend/src/style/GameRoom.css
- frontend/src/style/index.css
- frontend/src/style/presets/color.css
- frontend/src/util/Axios.ts
- frontend/src/util/Socket.ts
- #171 완료
- color 값들 변수화했습니다. `var(변수명)` 으로 CSS 에서 사용하시면 됩니다.
- `frontend/.env` 파일 만드시고 `VITE_X_USER_ID` 변수에 사용하고자 하시는 userId 넣어서 사용하시면 됩니다. .env Vite 가 다 해주더라고요! 원하면 MODE 별로 나눌 수 있는데 굳이 그럴 필요가 없다고 판단했습니다. env variable 추가해서 사용하고 싶으시면 `VITE_` prefix 를 꼭 붙여주셔야합니다. 해당 prefix 가 있는 변수들만 `import.meta.env.변수명` 으로 script 로 접근 가능합니다. 궁금하시면 이 [링크](https://vitejs.dev/guide/env-and-mode.html) 참조하세요 :)
close #171
> :hammer: chore : color 변수화 & x-user-id env 로 적용

- backend/src/main.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/user-relationship.storage.spec.ts
- backend/src/user-status/user-relationship.storage.ts
- backend/src/user-status/user-status.module.ts
- backend/src/user/user.gateway.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.spec.ts
- backend/test/user.e2e-spec.ts
- #164 완료
- 이제 e2e 테스트 한꺼번에 돌리면 간간히 터집니다. 하나씩 돌리면 다 괜찮습니다. 다 하나씩 돌렸봤습니다...
- #176 완료
- 유저 WS connection 시 받은 친구요청 개수 `friendRequestDiff` 로 전송.
- 개발 환경일 경우 Access-Control-Expose-Headers 에 'location' 헤더 필드 더하여서 CORS 여도 클라이언트가 해당 헤더 필드 접근 가능하게 설정.
close #164
close #176
> ✨ feat : 서비스 미접속 기간 동안 받은 친구 요청 전달

- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/activity.manager.spec.ts
- backend/src/user-status/activity.manager.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
- backend/test/activity-gateway.e2e-spec.ts
- backend/test/user.e2e-spec.ts
- #165  완료.
- 유저가 `GET /user/:userId/info` 요청을 friendToggleList 에서 보내는지 여부에 대한 확인이 필요하여 [`friendListOpened`](https://www.notion.so/WebSocket-API-v2-a2be4fca0aad467c83f83005c6a8352d?pvs=4#209d5a0ea15649489a9da2efa4d792fc) & [`friendListClosed`](https://www.notion.so/WebSocket-API-v2-a2be4fca0aad467c83f83005c6a8352d?pvs=4#1d2c9e4799da4c80aaddd70d8144565d) 이벤트를 만들었습니다.
- 클라이언트는 friendToggleList 가 열릴 때 `friendListOpened` 이벤트를, 닫힐 때 `friendListClosed` 이벤트를 보내주시면 됩니다.
- 이외에 클라이언트 쪽에서 바뀌어야하는 부분은 없을 것 같습니다.
- 드디어 진정한 스토킹 서비스로 거듭났습...아악...!!
- ActivityManager 에서 특정 UI & friendList 에서 보여지고 있는 유저마다 보고 있는 유저들 저장.
- ActivityManager 에서 friendToggleList 를 열어두고 있는 유저들 저장.
- 위 정보 기반으로 소켓 room 관리하여 특정 유저의 activity 가 변경되었을 때, 해당 유저의 유저 컴포넌트를 보고 있는 유저들에게만 `userActivity` 이벤트가 발송되게 구현.
close #165
> ✨ feat : 유저 컴포넌트를 보고 있는 유저에게만 activity 변경 정보 전달 #165

- frontend/src/components/chats/Channel.tsx
- frontend/src/components/chats/ChannelCreate.tsx
- frontend/src/components/chats/ChannelCreateForm.tsx
- frontend/src/components/chats/ChannelSvg.tsx
- frontend/src/components/chats/ChatsBody.tsx
- frontend/src/components/chats/ChatsFrame.tsx
- frontend/src/components/chats/FormModal.tsx
- frontend/src/components/chats/PasswordForm.tsx
- frontend/src/components/chats/interface.ts
- frontend/src/style/Chats.css
- frontend/src/style/FormModal.css
- frontend/src/style/presets/Alert.css
- frontend/src/style/presets/reset.css
- frontend/src/util/Alert.ts
- frontend/src/views/Chats.tsx
- #188 완료
- #189 완료
- Axios 성공 / 실패시 적절한 모달 추가
- Chats UI / FormModal 에 Style 및 Animation 적용
- SweetAlert2 와 최대한 유사하게 하려고 했지만... 모달이 닫힐 때 Animation 구현은 실패했습니다. 방법은 있는데 좀... 복잡합니다.
- svg 를 코드 가독성을 유지하며 사용하기 위해 Component 로 Wrapping 해서 사용했습니다. 추후에 search 에 있는 svg 도 업데이트 해두겠습니다.
- 재사용성을 위해서 일단은 svg component 에 prop 으로 여러 속성을 받아두었습니다. 
- 알림은 999개 이상 쌓이면 999+ 로 렌더링 되도록 하였습니다. 제한을 두지 않으면 UI 가 깨질 위험이 있습니다.
- 이미 접속한 채널 / 공개 채널을 클릭하면 바로 입장하도록 구현되어 있었는데, 모달 창을 거쳐서 입장하는 것으로 변경했습니다. 의도치 않게 잘못눌러서 들어가면 당황스러울 것 같았습니다... ㅎ
> ✨  feat : chats Axios 에러 핸들링 및 style 적용

- backend/src/game/interceptor/game-start.interceptor.ts
- backend/src/game/interceptor/ladder-queue.interceptor.ts
- frontend/src/App.tsx
- frontend/src/UserIdInput.test.tsx
- frontend/src/components/GameRoom/GameMenu.tsx
- frontend/src/components/GameRoom/GamePlay.tsx
- frontend/src/components/GameRoom/hooks/GameDataHooks.tsx
- frontend/src/components/User.tsx
- frontend/src/components/UserBase.tsx
- frontend/src/components/WaitingRoom/GameInProgressButton.tsx
- frontend/src/components/WaitingRoom/GameQueueButton.tsx
- frontend/src/components/WaitingRoom/GamesList.tsx
- frontend/src/components/common/FriendsList.tsx
- frontend/src/components/hooks/EmitCurrentUi.tsx
- frontend/src/style/App.css
- frontend/src/style/WaitingRoom.css
- frontend/src/util/Alert.ts
- frontend/src/util/Axios.ts
- frontend/src/util/Socket.ts
- frontend/src/views/Chats.tsx
- frontend/src/views/GameRoom.tsx
- frontend/src/views/Ranks.tsx
- frontend/src/views/WaitingRoom.tsx
- #187 진행 중입니다.
- #197 진행 중입니다.
- #198 완료. 
- #199 완료.
- socket connection 확인 후, 'currentUi' 발송하는 `useCurrentUi` hook 구현.
- 대기큐 접속, 대기 취소 구현.
- 매칭되면 게임방으로 이동 및 게임방에서 게임 정보 요청.
- 새게임 시작되거나, 게임 끝났을 때 진행 중인 게임 목록에 반영.
- 게임 시작 큐에서 매칭된 후 timeout 발생하던 문제 fix.
- input box 로 임시 유저 id 설정, sessionStorage 로 관리.
- 탭마다 다른 유저로 사용 가능합니다.
- gameStarted, gameEnded 이벤트 적용.
- 게임 관전 UI 이동.
- 게임방에서 게임 시작, 관전, gameAborted, gameCancelled 이벤트 적용.
- socket event on 하는 promise wrapper 를 만들면서 `export default socket` 을 `export socket` 로 수정했습니다.
- 게임 대기큐 접속, 대기 취소 UI.
https://user-images.githubusercontent.com/83805691/222435490-8b4fd86f-d6f9-451c-bd58-06a169aeef09.mov
> ✨ feat : 게임 데이터 흐름 추가 DRAFT

- backend/src/game/game.engine.ts
- backend/src/game/game.gateway.ts
- backend/src/util/type.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/GameRoom/GameMenu.tsx
- frontend/src/components/GameRoom/GamePlay.tsx
- frontend/src/components/GameRoom/hooks/GameDataHooks.tsx
- frontend/src/components/GameRoom/hooks/GamePlayHooks.tsx
- frontend/src/components/GameRoom/util/GamePainter.ts
- frontend/src/components/WaitingRoom/GameInProgressButton.tsx
- frontend/src/components/WaitingRoom/GameQueueButton.tsx
- frontend/src/components/hooks/EmitCurrentUi.tsx
- frontend/src/util/Recoils.ts
- frontend/src/util/Socket.ts
- frontend/src/views/GameRoom.tsx
- #216 해결.
- #217 완료.
- 게임 비정상 종료 시 서버에서 게임 엔진이 멈추도록 수정.
- 게임 비정상 종료 시 클라이언트 사이드에서 승자, 패자, 관전자에게 에러 메시지 상황에 맞게 설정.
- 게임 종료 후 waitingRoom 으로 이동.
- isPlayer, isStarted 상태가 새로고침 후에도 필요한 경우가 있어서 sessionStorage 에 저장했습니다.
close #216 
close #217
> :sparkles: feat : 게임 종료 후 UX 개선

- backend/src/chats/chats.controller.ts
- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.spec.ts
- backend/src/chats/chats.service.ts
- backend/src/chats/dto/chats.dto.ts
- backend/src/chats/guard/channel-owner.guard.ts
- backend/src/chats/pipe/message-transform.pipe.ts
- backend/src/chats/pipe/validate-channel-info.pipe.ts
- backend/src/user-status/channel.storage.ts
- backend/test/chats-gateway.e2e-spec.ts
- backend/test/chats.e2e-spec.ts
- #222 완료
- 채팅방에서 `/kick nickname` message 가 올 경우 해당 유저 영구 벤
- 142 년 BAN 으로 구현해뒀습니다.
- 채팅방 정보 수정하는 `PATCH /chats/:channelId` 를 구현했습니다.
- API 구현을 미루려고 했는데, 채팅방 UI 에서 수정 버튼을 누르면 모달창(방만들기 모달창을 조금만 수정하면 됩니다.) 을 띄워주는 방식을 사용하여 요청을 보내면 적당할 것 같습니다. 채팅방 UI 가 어느정도 구현하면 제가 초대 버튼과 함께 만들어 보겠습니다.
- 채팅방 정보 수정에 따른 WebSocket event 전송
- 이미 렌더링 된 방 정보 수정은 `updateChannel` 이벤트에 데이터를 추가하는 형식으로 구현하였습니다.
- public/protected -> private || private -> public/protected 로 변경되는 상황에선 Chats UI 에서 방을 새로 그려줘야 하기 때문에 이벤트를 추가로 emit 해줍니다.
---
- AccessMode 변경에 따른 방 정보 렌더링 여부를 기존 channelCreated / channelDeleted 이벤트를 재활용하여 적용할 예정이였는데, 불가능하다는 것을 깨닫고 channelShown / channelHidden 이벤트로 분리했습니다
close #222
> ✨ feat : 채팅방 내부 기능 추가

- backend/src/chats/guard/member-messaging.guard.ts
- #243 완료
- 에러 메시지 수정
- Mute 된 유저가 메시지 전송을 하면 다음과 같은 메시지가 뜹니다.
```JSON
{
"statusCode": 403,
"message": "This user is muted, mute remains: 41 minutes",
"error": "Forbidden"
}
```
> ✨ feat : 채팅방에서 Mute 된 멤버가 메시지 전송시 에러 메시지 수정

- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.spec.ts
- backend/src/chats/dto/chats-gateway.dto.ts
- backend/test/chats-gateway.e2e-spec.ts
- 메시지의 내용을 `GET /chats/:channelId/message` 에선 contents, `newMessage` 에선 content 로 보내주던 문제를 해결하였습니다.
> :bug: fix : HTTP 와 Socket 에서 전달하는 message 타입이 다른 문제 해결

- backend/src/game/game.controller.ts
- backend/src/game/game.service.spec.ts
- backend/src/game/game.service.ts
- backend/src/game/guard/existing-game.guard.ts
- backend/src/game/guard/is-player.guard.ts
- backend/src/game/guard/ladder-restriction.guard.ts
- backend/src/game/interceptor/game-start.interceptor.ts
- backend/src/util/type.ts
- backend/test/game-gateway.e2e-spec.ts
- backend/test/game.e2e-spec.ts
- #255 완료.
- 일반 게임 초대 요청을 받은 유저가 거절했을 때 서버에서 게임을 삭제하는 API 구현했습니다.
- 기존 게임 service 에 있던 예외 처리들을 Guards 들로 분리했습니다.
close #255
> ✨ feat : 일반 게임 초대 거절 API

- backend/src/guard/mock-auth.guard.ts
- frontend/src/App.tsx
- frontend/src/components/ChatRoom/Message.tsx
- frontend/src/components/Rank/MyRank.tsx
- frontend/src/components/Rank/RanksList.tsx
- frontend/src/components/common/ErrorBoundary.tsx
- frontend/src/components/hooks/CurrentUi.tsx
- frontend/src/style/Ranks.css
- frontend/src/util/Axios.ts
- frontend/src/util/Recoils.ts
- frontend/src/views/Ranks.tsx
- #265 완료
- #270 완료
- MockAuthGuard  수정
- MockAuthGuard 에서 에러시 401 리턴 및 development 환경에서만 작동하도록 변경
- ErrorBoundary 구현
- [React 공식 문서](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries) 및 [ErrorBoundary Typescript reference](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/error_boundaries/) 를 보고 만들었습니다.
- Suspense 와 통일성을 위하여 fallback 를 Props 로 받아서, 에러시 fallback 를 렌더링 합니다.
- 브라우저 전체에 [unhandledrejection_event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) 및 [error_event](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event) 를 핸들링 하여 unhandled exception 을 막았습니다.
- axios interceptor 를 활용하여 401 응답 핸들링
- 모든 응답에 대하여 401 응답이 오면 /login 으로 redirection 됩니다.
- Socket 에러와 401 에러는 /login 페이지가 구현되어야 더 …
> :sparkles: feat : ErrorBoundary 및 Axios interceptor 를 활용한 Error handling 

- frontend/src/components/ChatRoom/ChatList.tsx
- frontend/src/style/ChatRoom.css
- frontend/src/style/FriendsList.css
- frontend/src/style/Profile/Achievements.css
- frontend/src/style/Profile/LadderProgressBar.css
- frontend/src/style/Profile/MatchHistoryList.css
- frontend/src/style/Profile/MenuBar.css
- frontend/src/style/Profile/Profile.css
- frontend/src/style/Profile/WinLossTotalCounter.css
- #299 완료
기존 반응형을 고려하지 않고 코드를 짠 후폭풍으로 이제야 레이아웃을 최종적으로 잡게 되었습니다.
- profile 탭이 화면 너비에 맞는 퍼센티지로 레이아웃이 줄어들게 변경했습니다.
- 사용하지 않는 코드 주석을 삭제했습니다.
- chatroom 내부의 css 코드를 일부 수정했으나 큰 차이는 없습니다....
- friendList 버튼의 z-index 값을 수정했습니다.
close #299
> 💄 style: profile 탭 반응형 적용 및 세세한 부분 수정

- backend/src/chats/chats.controller.ts
- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.ts
- backend/src/profile/profile.service.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/channel.storage.ts
- #310 완료
- 차단된 관계의 유저 메시지를 더이상 보내주지 않습니다.
- `GET /chats/:channelId/message` 에서 차단된 유저의 메시지는 제외하고 응답합니다.
- "newMesssage" 이벤트에서 차단된 유저의 메시지는 emit 하지 않습니다.
- "messageArrive" 이벤트에서 차단된 유저의 메시지는 emit 하지 않습니다.
- 차단된 유저의 메시지가 도착할 경우 unseenCount 를 업데이트 하지 않습니다.
- channelStorage 에서 user 를 load 시 차단된 유저의 메시지는 unseenCount 에 카운트 하지 않습니다.
close #310
> ✨ feat : 채팅방에서 차단된 관계에 있는 유저의 메시지 제외 후 전송

- backend/src/chats/chats.controller.ts
- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.ts
- backend/src/chats/guard/member-messaging.guard.ts
- backend/src/user/user.module.ts
- frontend/src/components/ChatRoom/ChatList.tsx
- frontend/src/components/Chats/PasswordForm.tsx
- frontend/src/components/Chats/interface.ts
- frontend/src/components/Rank/MyRank.tsx
- frontend/src/components/Search/SearchModalFooter.tsx
- frontend/src/components/Search/hooks/SearchKeyPress.tsx
- frontend/src/components/hooks/CurrentUi.tsx
- frontend/src/views/ChatRoom.tsx
- #329 구현
- 차단 및 차단 해제시 메시지 숨김 / 리렌더링
- #312 PR 로 서버 에서 차단된 유저의 메시지를 제외하고 응답을 보내줬는데, 차단 해제시 메시지를 다시 보여주기 위하여 롤백
- message 를 렌더링 하기 위하여 recoil 을 쓰기 때문에 해당 컴포넌트를 lazy 로 바꿔줬습니다.
- chatRooms 에서 socket 에 connect 되었을 때만 하위 컴포넌트가 렌더링 되도록 바꿨습니다.
- 차단된 유저의 메시지만 제외하고 보여주게 되면서, 더 보기 버튼이 메시지 100개 이하일때 활성화 됨
close #329
> ✨ feat : 차단 및 차단 해제 시 채팅방 메시지 실시간 업데이트 구현

- backend/src/chats/chats.service.ts
- backend/src/user-status/channel.storage.ts
- backend/src/user-status/user-relationship.storage.ts
- 소켓 disconnect 후 cache 가 필요한 요청이 오면 load 가 안되어 있기 때문에 500 에러를 던져줍니다.
> 🐛 fix : 소켓 disconnect 후 cache 가 필요한 요청 오면 500 에러

- frontend/src/components/Search/SearchModalBody.tsx
- search modal 에서 defaultProfile 에 확장자를 안붙여서 이미지가 깨지던 문제 해결
> :bug: fix : search modal 에서 default profile 깨지는 문제 해결
