brilliantshell/ft_transcendence

- backend/.eslintrc.js
- backend/.gitignore
- backend/.prettierrc
- backend/Dockerfile.dev
- backend/nest-cli.json
- backend/package-lock.json
- backend/package.json
- backend/src/app.controller.spec.ts
- backend/src/app.controller.ts
- backend/src/app.module.ts
- backend/src/app.service.ts
- backend/src/main.ts
- backend/test.js
- backend/test/app.e2e-spec.ts
- backend/test/jest-e2e.json
- backend/tsconfig.build.json
- backend/tsconfig.json
- backend 개발에 필요한 dependency 설치
- backend/Dockerfile.dev 에 @nestjs/cli 설치
- backend 디렉토리에 NestJs 프로젝트 생성
close #35
> :hammer: chore : NestJs 프로젝트 생성

- database/sql/init_db.sql
- #31 내용대로 DB 초기화 쿼리 업데이트
- `init_db.sql` 업데이트
- [DB 설계 노션 페이지](https://teal-grill-819.notion.site/DB-0390ec95162a4509aeb18cedbce3e7f2)에 ERD 및 논리적 모델링 업데이트
> 🔨 chore : DB 설계 수정

- backend/src/entity/achievements.entity.ts
- backend/src/entity/achievers.entity.ts
- backend/src/entity/banned-members.entity.ts
- backend/src/entity/blocked-users.entity.ts
- backend/src/entity/channel-members.entity.ts
- backend/src/entity/channels.entity.ts
- backend/src/entity/date-time.transformer.ts
- backend/src/entity/friends.entity.ts
- backend/src/entity/match-history.entity.ts
- backend/src/entity/messages.entity.ts
- backend/src/entity/users.entity.ts
- backend/src/user-status/channel.storage.spec.ts
- backend/src/user-status/channel.storage.ts
- backend/src/user-status/user-relationship.storage.spec.ts
- backend/src/user-status/user-relationship.storage.ts
- backend/src/util/type.ts
- backend/test/generate-mock-data.ts
- 채팅방과 유저 관계 SELECT 최적화를 위한 ChannelStorage 객체 구현.
- dependency resolution 단계에서 자동으로 초기값 캐싱을 위해 onModuleInit 적용.
- 채팅방 & 유저 관계 데이터 caching & DB CRUD.
- entity 클래스에서 column 들을 camelCase 로 표현.
- 변수명을 통일성 있게 유지하기 위해
- DB 에는 decorator 안에 명시해준 snake_case `name` 값으로 저장
> ✨ feat : 채팅방과 유저 관계 SELECT 최적화를 위한 ChannelStorage 객체 구현

- backend/src/user-status/activity.manager.spec.ts
- backend/src/user-status/activity.manager.ts
- backend/src/user-status/user-status.module.ts
- backend/src/util/type.ts
- #55 
- 여러 객체에서 참조 및 변경할 수 있어야하기 때문에 객체로 구현했습니다.
- get, set, delete 구현
> ✨ feat : 유저가 머무르고 있는 UI 정보 저장하는 ActivityManager 구현 #55

- backend/src/user-status/activity.gateway.ts
- #60 완료
- #62 의사코드 작성
- #60 , #62 기반으로 의사코드 작성
close #60
> :sparkles: feat : WS connection 인증 및 WS rooms 할당 의사코드 작성

- backend/package-lock.json
- backend/package.json
- backend/src/user-status/user-relationship.storage.spec.ts
- backend/src/user-status/user-relationship.storage.ts
- backend/src/user/dto/user-gateway.dto.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.gateway.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
- backend/test/db-resource-manager.ts
- backend/test/generate-mock-data.ts
- backend/test/user-gateway.e2e-spec.ts
- #75 작업중
- PR 이 너무 커지기 전에 먼저 한번 PR 합니다.
- 아래 API 비즈니스 로직 구현
- [`GET /user/{:userId}/info`](https://www.notion.so/API-v3-8bf20c7a4eaa49b0ba45cd1d59e518bc#09abff544c13439bbe55893b6f3213f7) (닉네임 & 프로필 사진 반환)
- [`PUT /user/{:userId}/dm`](https://www.notion.so/API-v3-8bf20c7a4eaa49b0ba45cd1d59e518bc#61ccf1171cd1482da28eb935adf26ca1) (DM 생성)
> ✨ feat : UserService 프로필 정보 반환 및 DM 방 생성

- backend/src/user/user.controller.ts
- [줄레님 comment](https://github.com/brilliantshell/ft_transcendence/pull/89#discussion_r1095577324) 대로 async-await 없애도 잘 돼어서 수정해서 올립니다. 프레임워크 좋네요!
- 작은 디테일 짚어주셔서 감사합니다 줄레님 :)
> :recycle: refactor : 불필요한 async await

- backend/src/entity/users.entity.ts
- backend/src/user/dto/user.dto.ts
- backend/test/user.e2e-spec.ts
- database/sql/init_db.sql
> ♻️ refactor : 설정한 프로필 사진이 없으면 profileImage: null 반환

- backend/src/entity/users.entity.ts
> 🐛 fix : Users entity 의 Unique constraint 가 의도와 다르게 작동

- backend/src/app.module.ts
- backend/src/entity/achievements.entity.ts
- backend/src/entity/match-history.entity.ts
- backend/src/profile/profile.module.ts
- backend/src/profile/profile.service.spec.ts
- backend/src/profile/profile.service.ts
- backend/test/generate-mock-data.ts
- #103 구현
- 프사 업로드 / 삭제는 nest.js 문서를 더 살펴봐야 할 것 같아서, 구현을 미뤄둔 상태입니다
- ProfileService 구현
- 앱 구동 후 Achievements entity 가 변경될 가능성이 적다고 판단하여 인덱싱 하였습니다.
> ✨ feat : profile 비즈니스 로직을 수행하는 ProfileService 구현 완료

- backend/.vscode/settings.json
- backend/src/game/dto/game.dto.ts
- backend/src/game/game.gateway.ts
- backend/src/game/game.module.ts
- backend/src/game/game.service.spec.ts
- backend/src/game/game.service.ts
- backend/src/game/game.storage.ts
- backend/src/util/type.ts
- backend/test/game-gateway.e2e-spec.ts
- backend/test/ranks-gateway.e2e-spec.ts
- #135 완료
- 아래 기능들의 비즈니스 로직 구현했습니다.
- 일반 게임 초대
- 게임 관전
- 게임 시작
- 맵 변경
- 진행 중인 게임 리스트
- 몇가지 error 핸들링, 대기열 관리 및 게임 동시 시작은 controller 구현하면서 interceptor 에서 처리해주려고 합니다.
- 게임 모듈 내부에서 자잘한 수정이 있었는데 다른 모듈에 영향 주는 변화는 딱히 없습니다.
close #135
> ✨ feat : 게임 관련 비즈니스 로직 수행하는 GameService 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/api/Axios.ts
- frontend/src/components/MyRank.tsx
- frontend/src/components/RankList.tsx
- frontend/src/components/User.tsx
- frontend/src/components/UserBase.tsx
- frontend/src/components/common/Header.tsx
- frontend/src/components/common/Main.tsx
- frontend/src/components/common/Navigation.tsx
- frontend/src/components/common/Routers.tsx
- frontend/src/style/Ranks.css
- frontend/src/style/UserBase.css
- frontend/src/util/Axios.ts
- frontend/src/util/Recoils.ts
- frontend/src/util/Socket.ts
- frontend/src/views/Ranks.tsx
- #148
- #149
- #150 
- 전역 상태 관리를 위한 `Recoil`적용
- atom에 default 값을 axios로 받아오는데 해당 처리가 비동기로 이뤄지기 때문에 해당 atom을 외부에서 받아올 때
- 값이 아직 처리가 안된 상태로 변수에 넣는 문제가 발생
- 해당 문제를 처리하기 위한 방법
-  react suspense
-  `useRecoilValueLoadable` 이걸로 문제 해결
- 기존의 디렉토리 구조에서 더 세분화하여 적용
- `/ranks` 페이지 구현
- 기존 계획에서는 ranking table을 scroll로 구현 예정
- 모든 랭킹을 보여주는 것보다 TOP 50정도만 보여주는 것이 더 좋을 것 같아서 수정
close #148 
close #149
> ✨ feat : /ranks 페이지 구현

- backend/src/game/dto/game-gateway.dto.ts
- backend/src/game/game.controller.ts
- backend/src/game/game.gateway.ts
- backend/src/game/game.service.spec.ts
- backend/src/game/game.service.ts
- backend/src/game/interceptor/game-start.interceptor.ts
- backend/src/user-status/activity.gateway.ts
- backend/test/game-gateway.e2e-spec.ts
- backend/test/game.e2e-spec.ts
- backend/test/user.e2e-spec.ts
- #156 완료
- #157 완료
- 구현 및 변경 이유는 [회의록에](https://teal-grill-819.notion.site/25FEB23-b413a90903634966a4e50eb511a46a43) 적어뒀습니다.
> ✨ feat : 게임 취소를 알리는 gameCancelled 이벤트 #156

- backend/Dockerfile.dev
- database/docker-entrypoint.dev.sh
- Backend 환경에 NODE_ENV 가 적용이 안되고 있어서 Dockerfile 에 NODE_ENV 추가
- DB entrypoint 스크립트에서 DB 에 데이터가 존재하지 않으면 삽입하도록 변경
> 🔨 chore : backend Dockerfile 에 ENV 추가 및 DB entrypoint script 수정

- backend/src/game/game.service.spec.ts
- 그냥 오타 수정입니다.
- 지금 안 하면 까먹을 것 같아 작고 귀여운 PR 보냅니다 ㅎㅎ
> :hammer: chore : 오타 수정

- frontend/src/components/GameRoom/GameInfo.tsx
- frontend/src/components/GameRoom/GameMenu.tsx
- frontend/src/components/GameRoom/GamePlay.tsx
- frontend/src/components/GameRoom/hooks/GamePlayHooks.tsx
- frontend/src/components/common/Routers.tsx
- frontend/src/style/App.css
- frontend/src/style/GameRoom.css
- frontend/src/style/presets/font.css
- frontend/src/style/presets/reset.css
- frontend/src/views/GameRoom.tsx
- #163 완성
- /game/example 로 가면 아래 스크린샷과 같이 보입니다.
- 게임방 반응형 layout 구현.
- reset.css 추가.
- 통일된 font style 적용을 위한 font.css 추가.
https://user-images.githubusercontent.com/83805691/221191189-4d87eb62-dfa2-4b61-ab76-f6381217aacc.mov
close #163
> ✨ feat : 게임 방 UI layout #163

- frontend/src/style/presets/reset.css
- 이전 reset.css 에 문제가 있어 변경
- 문제점
-  px 기반 font-size 사용
- 브라우저 속성을 reset 하기에 부족
- font-family 와 button 속성은 유지
> :lipstick: style : reset.css 변경

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/GameRoom/GamePlay.tsx
- frontend/src/components/GameRoom/hooks/GamePlayHooks.tsx
- frontend/src/components/GameRoom/hooks/GameResizeHooks.tsx
- frontend/src/components/GameRoom/util/GamePainter.ts
- frontend/src/components/GameRoom/util/interfaces.ts
- frontend/src/components/common/Routers.tsx
- frontend/src/style/App.css
- frontend/src/style/GameRoom.css
- frontend/src/style/presets/font.css
- frontend/src/style/search.css
- frontend/src/views/GameRoom.tsx
- #170 draft 입니다.
- 매 10 ms 마다 canvas 를 다시 그리는 상당히 무식... 아니 놀라운 구현입니다!! (이렇게 하라고 하더라고요...) 그래도 canvas element 자체가 re-render 되는 건 아닙니다. 
- 처음에 함수 범벅으로 구현했다가 도저히 못 보겠어서 클래스로 뽑아냈습니다. 데이터 흐름이 들어오면 어떻게 해야할지 도통 모르겠습니다...
- 실제 게임 데이터가 오고 가야 감이 잡힐 것 같아 waitingRoom 을 먼저 구현하려고 합니다.
- 데이터 흐름 없이 한쪽 paddle 만 움직이는, 오른쪽이 질 수 밖에 없는 탁구 게임입니다.
- 귀여운 폰트 적용했습니다.
P.S. - resize 할 때마다 게임이 재시작 됩니다 :D... 이건 추후에 recoil 사용하여 re-render 될 때 초기 위치를 잡아주는 방식으로 해결하려고 합니다.
> ✨ feat : 게임 플레이 UI 구현

- backend/src/chats/chats.service.spec.ts
- backend/src/chats/chats.service.ts
> 🐛 fix : Chats websocket 에 userId 와 channelId 가 반대로 전달

- backend/src/user-status/user-relationship.storage.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
- backend/test/user.e2e-spec.ts
- #200 완료.
- {friends, pendingSenders, pendingReceivers} 입니다. 끝에 's' 있으니 참고하세요 :)
close #200
> ♻️ GET /user/friend 수정 #200

- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/channel.storage.ts
- backend/src/user-status/user-relationship.storage.ts
- backend/test/chats.e2e-spec.ts
- frontend/src/components/chats/Channel.tsx
- frontend/src/components/chats/ChannelCreate.tsx
- frontend/src/components/chats/ChannelSvg.tsx
- frontend/src/components/chats/ChatsBody.tsx
- frontend/src/components/chats/ChatsFrame.tsx
- frontend/src/components/chats/FormModal.tsx
- frontend/src/components/chats/PasswordForm.tsx
- frontend/src/components/chats/hooks/ChannelHooks.tsx
- frontend/src/views/Chats.tsx
- #205 완료
- #206 해결
- ChatsGateway 에 emitBanned 추가
- listenEvent 함수에 event 를 한번만 듣는 문제가 있어서 socket.on 메소드로 수정
- ChatsGateway 의 channelCreated event 에서 message 중 name -> channelName 수정 (HTTP API 와 통일)
> ✨ feat : chats UI 를 보고 있는 유저가 Ban 당한 경우 이벤트 전송 

- backend/src/chats/chats.gateway.ts
- frontend/src/components/chats/ChannelCreate.tsx
- frontend/src/components/chats/ChannelSvg.tsx
- frontend/src/components/chats/ChatsFrame.tsx
- frontend/src/components/chats/FormModal.tsx
- frontend/src/components/chats/hooks/ChannelHooks.tsx
- frontend/src/style/index.css
- frontend/src/views/Chats.tsx
- #225 완료
- accessMode 변화에 따라 채팅방을 보여주거나, 삭제
- accessMode 변화에 따라 아이콘 변경
close #225
> ✨ feat :  chats UI 에서 방 정보 변경 event 적용 

- frontend/src/components/Profile/Achievements.tsx
- frontend/src/components/Profile/LadderProgressBar.tsx
- frontend/src/components/Profile/MatchHistoryList.tsx
- frontend/src/components/Profile/MenuBar.tsx
- frontend/src/components/Profile/WinLossTotalCounter.tsx
- frontend/src/style/Profile/index.css
- frontend/src/style/index.css
- frontend/src/views/Profile.tsx
- Profile.tsx에서 useCurrentUi가 import되지 않았던 부분 수정했습니다
- Profile 페이지에서 import되는 css 파일들을 index.css에 정리했습니다
close #234
> ♻️ useCurrentUi import 및 css index 파일 생성

- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.ts
- frontend/src/components/chats/hooks/ChannelHooks.tsx
- frontend/src/views/Chats.tsx
- #245 완료
- 채널 초대를 당하면, 참여한 채널에 채널을 추가
> ✨ feat : 채널에 초대받은 유저의 참여한 채널 목록 업데이트

- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.spec.ts
- backend/src/chats/chats.service.ts
- backend/src/chats/dto/chats-gateway.dto.ts
- backend/src/chats/guard/join-channel.guard.ts
- backend/src/user-status/channel.storage.ts
- backend/src/util/type.ts
- backend/test/chats-gateway.e2e-spec.ts
- #248 완료
- 채널의 메시지를 전송하는 경우 messageId 추가
- socket 으로 timestamp 를 전송하는 경우와 HTTP 로 전송하는 경우 timestamp 형태 통일
---
데이터 form 은 #248 에 정리해뒀고, Notion 에 수정해두겠습니다.
> ✨ feat : 응답으로 message 를 전송 하는 경우 messageId 추가 #248

- backend/src/profile/profile.service.spec.ts
- backend/src/profile/profile.service.ts
- #267 해결
- 프사가 삭제되면 isDefaultImage 는 true 입니다.
- 프사가 생성되면 isDefaultImage 는 false 입니다.
> 🐛 fix : 프로필 사진이 설정시 isDefaultImage 정확히 설정

- .gitignore
- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/channel.storage.ts
- frontend/src/App.tsx
- frontend/src/components/FriendsList/FriendsList.tsx
- frontend/src/components/common/Header.tsx
- frontend/src/style/Login.css
- frontend/src/views/Login.tsx
- #273 완료
- #276 해결
- 로그인 UI 구현
- 브라우저를 통하여 직접 링크를 바꿔주는 형태입니다... production 환경에선 axios 로 요청을 날려봤는데, CORS 에러가 뜹니다. 서버에서 api.intra.42.fr 에 CORS 를 풀어줘도 해결이 안됩니다. sign-up UI 구현하고 해결해보겠습니다.
- accessToken 이 만료된 경우 소켓 요청과 `GET /user/id` 요청이 동시에 날아가면서 refreshToken 을 두번 조회하게 되어 인증이 실패하는 버그가 있습니다. 소켓 연결 이후 `GET /user/id` 요청 보내도록 보장해주면 잘 작동합니다. 조만간 수정하겠습니다.
- 현재 CSS 와 React component 구조 상 login UI 렌더링이 애매해져서 AppWrapper 를 만들었습니다.
close #276
close #273
> :sparkles: feat : 로그인 UI 구현 완료

- docker-compose.yml
- #284 해결
- asset 을 위한 docker volume 을 생성하여 profile-image 파일들 유지
> 🐛 fix : docker production 환경에서 업로드한 이미지 유지

- docker-compose.yml
- frontend/src/AppWrapper.tsx
- frontend/src/components/Chats/ChatsBody.tsx
- frontend/src/components/Search/SearchModalBody.tsx
- frontend/src/components/common/PublicRoutes.tsx
- frontend/src/style/Chats.css
- frontend/src/style/presets/general.css
- frontend/src/util/Axios.ts
- frontend/src/views/Chats.tsx
- frontend/src/views/SignUp.tsx
- 각종 사소한 버그 fix
- search 에서 유저 프사 링크가 잘못 지정되던 문제 해결
- Suspense 시 spin 렌더링
- 채널 목록에서 방만들기 버튼이 자리를 차지하던 문제 해결
- Axios interceptor 에서 500 이상 에러 핸들링
- docker volume 타겟을 /app/public/assets/ -> /app/public/assets/profile-image 변경
- /assets 를 타겟으로 잡으면 이전에 저장된 dist 파일이 같이 남아서 에러가 납니다
> :bug: fix : 사소한 버그들 fix

- frontend/src/components/FriendsList/Content.tsx
- frontend/src/components/FriendsList/FriendsList.tsx
- frontend/src/components/User/BlockButton.tsx
- frontend/src/components/User/Dropdown.tsx
- frontend/src/components/User/FriendButton.tsx
- frontend/src/components/User/GameButton.tsx
- frontend/src/components/User/User.tsx
- frontend/src/components/User/UserBase.tsx
- frontend/src/components/common/NotFoundComponent.tsx
- frontend/src/components/common/Routers.tsx
- frontend/src/main.tsx
- frontend/src/style/App.css
- frontend/src/style/FriendsList.css
- frontend/src/style/User.css
- frontend/src/style/UserBase.css
- frontend/src/views/GameRoom.tsx
- #291 완료.
- #292 완료.
- #295 완료.
https://user-images.githubusercontent.com/83805691/225281096-3a585ac8-6122-4244-9643-a1bc68f0a545.mov
close #291 
close #292 
close #295
> :sparkles: feat : 전체적인 ui & ux 개선

- frontend/src/components/Profile/ChangeNickname.tsx
- frontend/src/components/Profile/DeleteImage.tsx
- frontend/src/components/Profile/LadderProgressBar.tsx
- frontend/src/components/Profile/UploadImage.tsx
- frontend/src/components/User/FriendButton.tsx
- frontend/src/components/User/UserBase.tsx
- frontend/src/util/Alert.ts
- frontend/src/util/Recoils.ts
- frontend/src/views/Profile.tsx
- #300 완료
- atom을 사용하여 리랜더링
- 닉네임 영문만 입력 가능하게 수정
- 미흡한 에러처리 수정
close #300
> ✨ feat: 닉네임, 프로필 변경 시 리랜더링

- backend/src/login/login.module.ts
- backend/src/login/login.service.ts
- backend/src/profile/profile.module.ts
- backend/src/profile/profile.service.spec.ts
- backend/src/profile/profile.service.ts
- backend/src/user/user.controller.ts
- #296 완료
- #303 완료
- profile 을 조회할 때 새로 달성된 업적이 존재하는지 확인하고 업데이트 합니다.
- 4번 업적 (42 번째 유저) 는 회원 가입 시 체크됩니다.
- #303 이슈는 UserController 에서 async 함수 호출에 대한 return 을 명시해줘서 해결했습니다.
> ✨ feat : 업적 달성 구현 및 Users Controller 버그 수정

- backend/src/auth/jwt-auth.io-adapter.ts
- frontend/src/components/Profile/ProfileContainer.tsx
- frontend/src/style/ChatRoom.css
- frontend/src/style/UserBase.css
- frontend/src/views/ChatRoom.tsx
- frontend/src/views/Profile.tsx
- #305 해결
- #306 해결
- #307 해결
- #308 해결
- #305 -> profile component 에서 undefined 가 리턴되는 경우가 있어 해결
- #306 -> profileImage 가 있는 div 에 width 와 height 를 줘서 해결
- #307 -> ProfileContainer Component 로 Wrapping 하여 소켓 연결이 되었을 때 HTTP 요청을 날리도록 수정
- #308 -> undefined 가 나오면 empty string 으로 치환
> :bug: fix : 각종 버그 해결

- frontend/src/components/common/Navigation.tsx
- frontend/src/components/common/PublicRoutes.tsx
- frontend/src/style/TwoFA.css
- frontend/src/style/index.css
- frontend/src/views/TwoFactorAuth.tsx
- #283 완료.
https://user-images.githubusercontent.com/83805691/225542527-ec267d2e-73c1-47a7-a476-95c8925bdc48.mov
> ✨ feat : 2FA 페이지 구현

- frontend/src/components/ChatRoom/ChannelInvitationButton.tsx
- frontend/src/components/ChatRoom/ChatList.tsx
- frontend/src/components/ChatRoom/UserLeftButton.tsx
- frontend/src/components/ChatRoom/UserList.tsx
- frontend/src/components/FriendsList/FriendsList.tsx
- frontend/src/components/FriendsList/UserPendingReceivers.tsx
- frontend/src/components/Profile/Achievements.tsx
- frontend/src/components/Profile/MatchHistoryList.tsx
- frontend/src/components/Profile/TwoFASetting.tsx
- frontend/src/style/ChatRoom.css
- frontend/src/style/FriendsList.css
- frontend/src/style/presets/color.css
- frontend/src/util/Alert.ts
- #221 완료
- css 개선
- 2FA 이메일 등록 alert에서 esc누르거나 다른 영역 눌렀을 때도 patch를 보내서 뜨는 에러를 patch 안보내는 것으로 수정
> 💄 style: ChatRoom, FriendList UI 수정

- frontend/src/components/ChatRoom/ChatInput.tsx
- frontend/src/components/ChatRoom/UserList.tsx
- frontend/src/style/ChatRoom.css
✨ feat: chatRoom UI #221 - 진행중
🐛 : fix: chatroom에서 메시지 전송 시 발생 가능한 400번대 에러 처리 #317 - 완료
🐛 fix: chatroom에서 /role 명령어 사용 시 발생하는 오류 해결 #318 - 완료
✨ feat: chatRoom UI
- 채팅방 유저들의 목록을 가운데 정렬하는 css 코드를 추가했습니다.
🐛 : fix: chatroom에서 메시지 전송 시 발생 가능한 400번대 에러 처리
- 기존에는 chatroom 안에서 발생하는 몇 가지 에러 케이스를 놓치고 있었습니다 (mute 당한 유저에게 남은 채팅 금지 시간을 알려주는 부분만 처리되어 있었음)
- alertMessage 케이스별로 분기를 나누어 ErrorAlert를 해 주었습니다.
🐛 fix: chatroom에서 /role 명령어 사용 시 발생하는 오류 해결
- 기존에는 channelMembers 전체를 copy하고 index를 탐색해 해당 유저의 권한을 변경해 준 뒤 setChannelMembers(copy)를 통해 status를 변경해 주었습니다.
- 해당 index의 role만 변경해주는 방식으로 수정했습니다.
close #317 
close #318
> 🐛 fix: chatroom에서 발생하는 오류 해결 및 스타일 개선

- backend/src/auth/jwt-auth.io-adapter.ts
- backend/src/chats/chats.module.ts
- backend/src/chats/chats.service.ts
- backend/src/main.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/user-status/channel.storage.ts
- #320 해결
- 이전 handleConnection 에서 유저 정보를 load 했었는데, IoAdapter 로 옮겼습니다.
- socket 연결을 시작하는 첫 요청에서 유저 정보를 load 합니다.
- load 메소드 call 하는 위치 변경
> 🐛 fix : 유저 로그인 시 storage 에 load 하는 시점 변경하여 #320 해결

- frontend/src/components/ChatRoom/ChannelUpdateButton.tsx
- frontend/src/components/ChatRoom/ChatList.tsx
- frontend/src/components/ChatRoom/Message.tsx
- frontend/src/components/ChatRoom/UserList.tsx
- frontend/src/components/User/UserBase.tsx
- frontend/src/components/hooks/CurrentUi.tsx
- frontend/src/style/ChatRoom.css
- frontend/src/style/presets/color.css
- frontend/src/util/Recoils.ts
- frontend/src/views/ChatRoom.tsx
- #221 완료
- #315 완료
- #316 완료
- #322 
- ChatRoom에서 owner일 때 보이는 '수정'버튼 css 적용
- inGame일 때 activity 주황색으로 보이기
- 기존의 sessionStorage를 atomFamily로 수정
- dm방일 때 alert 뜨는 부분 안뜨도록 조건문에 조건 추가
- dm방에서 처음 dm을 보낸(owner로 적용된..?) 사람이 나가는 경우 상대방 dm방도 사라집니다.
close #221
close #315
close #316
close #322
> 🐛 fix: chatRoom에서 나오는 버그 수정

- backend/src/chats/chats.gateway.ts
- backend/src/chats/chats.service.ts
- backend/src/user-status/channel.storage.spec.ts
- backend/src/user-status/channel.storage.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.ts
- frontend/src/components/Chats/hooks/ChannelHooks.tsx
- frontend/src/views/Chats.tsx
- #323 수정
- Chats UI 에서 일반 chatRoom 과 다르게 Dm 채널은 대부분의 이벤트가 안먹어서 적용해줬습니다.
- 백엔드에서 DM 방일 때 두 멤버의 Role 을 member 로 만들었습니다.
> 🐛 fix : DM 방 관련 Chats UI 버그 수정 #323

- backend/src/game/game.controller.ts
- backend/src/game/game.service.ts
- backend/src/game/game.storage.ts
- backend/src/game/guard/spectator-block.guard.ts
- backend/src/user-status/activity.gateway.ts
- backend/src/util/type.ts
- frontend/src/components/GameRoom/GameMenu.tsx
- frontend/src/components/GameRoom/GameOption.tsx
- frontend/src/components/GameRoom/GameOptionForm.tsx
- frontend/src/components/GameRoom/GamePlay.tsx
- frontend/src/components/GameRoom/hooks/GameDataHooks.tsx
- frontend/src/components/GameRoom/hooks/GamePlayHooks.tsx
- frontend/src/components/GameRoom/util/GamePainter.ts
- frontend/src/components/GameRoom/util/interfaces.ts
- frontend/src/components/User/GameButton.tsx
- frontend/src/components/WaitingRoom/GameInProgressButton.tsx
- frontend/src/components/WaitingRoom/GameQueueButton.tsx
- frontend/src/components/common/Main.tsx
- frontend/src/components/hooks/CurrentUi.tsx
- frontend/src/util/Recoils.ts
- frontend/src/views/GameRoom.tsx
- #314 완료
- @kimhankyu 님께서 헤어지기전 주신 영감을 받아 만악의 근원 sessionStorage 를 없애고, 매 새로고침마다 서버가 보내주는 상태를 사용하는 것으로 수정했습니다.
- `GET /game/list/:gameId` 를 `GET /game/:gameId` 와 통합했습니다.
- 네트워크 연결이 끊겨도 게임이 유지됩니다.
- 많은 테스트 부탁드립니다...
- #327 완료
close #314
close #327
> :sparkles: feat : 게임 재연결

- frontend/src/components/ChatRoom/ChatInput.tsx
- 4096글자 이상일 때 나오는 alert 문구 수정
- 조건문에 조건 추가
> 🐛 fix: 4096글자 이상일 때 나오는 alert 문구 수정

- frontend/src/components/ChatRoom/ChatInput.tsx
- frontend/src/style/ChatRoom.css
> :lipstick: style : 채팅룸 style 수정 ##331

- frontend/src/style/Profile/MatchHistoryList.css
- height, width 를 max-height, max-width 로 수정
> :lipstick: style : MatchHistory 에서 프로필 사진 비율 수정 #337

- backend/src/auth/jwt-auth.io-adapter.ts
- backend/src/chats/chats.module.ts
- backend/src/chats/chats.service.spec.ts
- backend/src/profile/profile.service.spec.ts
- backend/src/user-status/channel.storage.spec.ts
- backend/src/user/user.service.spec.ts
- backend/test/auth.e2e-spec.ts
- backend/test/chats-gateway.e2e-spec.ts
- backend/test/chats.e2e-spec.ts
- backend/test/jest-e2e.json
- backend/test/login.e2e-spec.ts
- backend/test/profile.e2e-spec.ts
- 최종 변경 사항에 맞춰 테스트에 반영해뒀습니다.
- unit test 는 game 빼고 다 작동합니다.
- e2e 테스트는 아래에 있는 친구들이 다 작동합니다.
> ✅  test :  테스트에 최종 변경 사항 반영

- README.md
> :memo: docs : 노션 링크 추가
